---
- name: Ensure iTerm2 config directory exists
  file:
    path: "~/Library/Application Support/iTerm2"
    state: directory
    mode: '0755'

- name: Copy iTerm2 preferences
  copy:
    src: "files/iterm2/{{ iterm_colors }}"
    dest: "~/Library/Application Support/iTerm2/{{ iterm_colors }}"
    mode: '0644'
  when: configure_iterm

- name: Add iTerm2 profile switching function to .zshrc
  lineinfile:
    path: ~/.zshrc
    line: 'it2prof() { echo -e "\033]50;SetProfile=$1\a" }'
    state: present
  when: configure_iterm

- name: Set iTerm2 color profile
  shell: |
    it2prof "{{ iterm_colors | splitext | first }}"
  when: configure_iterm
